/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding/success'
import { Route as OnboardingStep4RouteImport } from './routes/onboarding/step-4'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding/step-3'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding/step-2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step-1'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppChildrenIndexRouteImport } from './routes/_app/children/index'
import { Route as AppChildrenAddRouteImport } from './routes/_app/children/add'
import { Route as AppChildrenAthleteIdRouteImport } from './routes/_app/children/$athleteId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep4Route = OnboardingStep4RouteImport.update({
  id: '/step-4',
  path: '/step-4',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/step-3',
  path: '/step-3',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/step-2',
  path: '/step-2',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/step-1',
  path: '/step-1',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenIndexRoute = AppChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenAddRoute = AppChildrenAddRouteImport.update({
  id: '/children/add',
  path: '/children/add',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenAthleteIdRoute = AppChildrenAthleteIdRouteImport.update({
  id: '/children/$athleteId',
  path: '/children/$athleteId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/messages': typeof AppMessagesRoute
  '/profile': typeof AppProfileRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/children/$athleteId': typeof AppChildrenAthleteIdRoute
  '/children/add': typeof AppChildrenAddRoute
  '/children/': typeof AppChildrenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/billing': typeof AppBillingRoute
  '/dashboard': typeof AppDashboardRoute
  '/messages': typeof AppMessagesRoute
  '/profile': typeof AppProfileRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/children/$athleteId': typeof AppChildrenAthleteIdRoute
  '/children/add': typeof AppChildrenAddRoute
  '/children': typeof AppChildrenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/profile': typeof AppProfileRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/_app/children/$athleteId': typeof AppChildrenAthleteIdRoute
  '/_app/children/add': typeof AppChildrenAddRoute
  '/_app/children/': typeof AppChildrenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/billing'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/success'
    | '/children/$athleteId'
    | '/children/add'
    | '/children/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/billing'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/success'
    | '/children/$athleteId'
    | '/children/add'
    | '/children'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/messages'
    | '/_app/profile'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/success'
    | '/_app/children/$athleteId'
    | '/_app/children/add'
    | '/_app/children/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step-4': {
      id: '/onboarding/step-4'
      path: '/step-4'
      fullPath: '/onboarding/step-4'
      preLoaderRoute: typeof OnboardingStep4RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step-3': {
      id: '/onboarding/step-3'
      path: '/step-3'
      fullPath: '/onboarding/step-3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step-2': {
      id: '/onboarding/step-2'
      path: '/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/step-1': {
      id: '/onboarding/step-1'
      path: '/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/children/': {
      id: '/_app/children/'
      path: '/children'
      fullPath: '/children/'
      preLoaderRoute: typeof AppChildrenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/children/add': {
      id: '/_app/children/add'
      path: '/children/add'
      fullPath: '/children/add'
      preLoaderRoute: typeof AppChildrenAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/children/$athleteId': {
      id: '/_app/children/$athleteId'
      path: '/children/$athleteId'
      fullPath: '/children/$athleteId'
      preLoaderRoute: typeof AppChildrenAthleteIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppChildrenAthleteIdRoute: typeof AppChildrenAthleteIdRoute
  AppChildrenAddRoute: typeof AppChildrenAddRoute
  AppChildrenIndexRoute: typeof AppChildrenIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppProfileRoute: AppProfileRoute,
  AppChildrenAthleteIdRoute: AppChildrenAthleteIdRoute,
  AppChildrenAddRoute: AppChildrenAddRoute,
  AppChildrenIndexRoute: AppChildrenIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  OnboardingStep3Route: typeof OnboardingStep3Route
  OnboardingStep4Route: typeof OnboardingStep4Route
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  OnboardingStep3Route: OnboardingStep3Route,
  OnboardingStep4Route: OnboardingStep4Route,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
