/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as TermsPrivacyRouteImport } from './routes/terms-privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EducationFaqRouteImport } from './routes/education-faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding/success'
import { Route as OnboardingStep5RouteImport } from './routes/onboarding/step-5'
import { Route as OnboardingStep4RouteImport } from './routes/onboarding/step-4'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding/step-3'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding/step-2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step-1'
import { Route as OnboardingDashboardRouteImport } from './routes/onboarding/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsPrivacyRoute = TermsPrivacyRouteImport.update({
  id: '/terms-privacy',
  path: '/terms-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationFaqRoute = EducationFaqRouteImport.update({
  id: '/education-faq',
  path: '/education-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/onboarding/success',
  path: '/onboarding/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep5Route = OnboardingStep5RouteImport.update({
  id: '/onboarding/step-5',
  path: '/onboarding/step-5',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep4Route = OnboardingStep4RouteImport.update({
  id: '/onboarding/step-4',
  path: '/onboarding/step-4',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/onboarding/step-3',
  path: '/onboarding/step-3',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/onboarding/step-2',
  path: '/onboarding/step-2',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/onboarding/step-1',
  path: '/onboarding/step-1',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDashboardRoute = OnboardingDashboardRouteImport.update({
  id: '/onboarding/dashboard',
  path: '/onboarding/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/education-faq': typeof EducationFaqRoute
  '/login': typeof LoginRoute
  '/terms-privacy': typeof TermsPrivacyRoute
  '/verification': typeof VerificationRoute
  '/onboarding/dashboard': typeof OnboardingDashboardRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/onboarding/step-5': typeof OnboardingStep5Route
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/education-faq': typeof EducationFaqRoute
  '/login': typeof LoginRoute
  '/terms-privacy': typeof TermsPrivacyRoute
  '/verification': typeof VerificationRoute
  '/onboarding/dashboard': typeof OnboardingDashboardRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/onboarding/step-5': typeof OnboardingStep5Route
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/education-faq': typeof EducationFaqRoute
  '/login': typeof LoginRoute
  '/terms-privacy': typeof TermsPrivacyRoute
  '/verification': typeof VerificationRoute
  '/onboarding/dashboard': typeof OnboardingDashboardRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/onboarding/step-5': typeof OnboardingStep5Route
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/education-faq'
    | '/login'
    | '/terms-privacy'
    | '/verification'
    | '/onboarding/dashboard'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/step-5'
    | '/onboarding/success'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/education-faq'
    | '/login'
    | '/terms-privacy'
    | '/verification'
    | '/onboarding/dashboard'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/step-5'
    | '/onboarding/success'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/education-faq'
    | '/login'
    | '/terms-privacy'
    | '/verification'
    | '/onboarding/dashboard'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/step-5'
    | '/onboarding/success'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EducationFaqRoute: typeof EducationFaqRoute
  LoginRoute: typeof LoginRoute
  TermsPrivacyRoute: typeof TermsPrivacyRoute
  VerificationRoute: typeof VerificationRoute
  OnboardingDashboardRoute: typeof OnboardingDashboardRoute
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  OnboardingStep3Route: typeof OnboardingStep3Route
  OnboardingStep4Route: typeof OnboardingStep4Route
  OnboardingStep5Route: typeof OnboardingStep5Route
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-privacy': {
      id: '/terms-privacy'
      path: '/terms-privacy'
      fullPath: '/terms-privacy'
      preLoaderRoute: typeof TermsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-faq': {
      id: '/education-faq'
      path: '/education-faq'
      fullPath: '/education-faq'
      preLoaderRoute: typeof EducationFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/onboarding/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-5': {
      id: '/onboarding/step-5'
      path: '/onboarding/step-5'
      fullPath: '/onboarding/step-5'
      preLoaderRoute: typeof OnboardingStep5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-4': {
      id: '/onboarding/step-4'
      path: '/onboarding/step-4'
      fullPath: '/onboarding/step-4'
      preLoaderRoute: typeof OnboardingStep4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-3': {
      id: '/onboarding/step-3'
      path: '/onboarding/step-3'
      fullPath: '/onboarding/step-3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-2': {
      id: '/onboarding/step-2'
      path: '/onboarding/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-1': {
      id: '/onboarding/step-1'
      path: '/onboarding/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/dashboard': {
      id: '/onboarding/dashboard'
      path: '/onboarding/dashboard'
      fullPath: '/onboarding/dashboard'
      preLoaderRoute: typeof OnboardingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EducationFaqRoute: EducationFaqRoute,
  LoginRoute: LoginRoute,
  TermsPrivacyRoute: TermsPrivacyRoute,
  VerificationRoute: VerificationRoute,
  OnboardingDashboardRoute: OnboardingDashboardRoute,
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  OnboardingStep3Route: OnboardingStep3Route,
  OnboardingStep4Route: OnboardingStep4Route,
  OnboardingStep5Route: OnboardingStep5Route,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
