/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as TermsPrivacyRouteImport } from './routes/terms-privacy'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EducationFaqRouteImport } from './routes/education-faq'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTrackingRouteImport } from './routes/portal/tracking'
import { Route as PortalScheduleRouteImport } from './routes/portal/schedule'
import { Route as PortalMoreRouteImport } from './routes/portal/more'
import { Route as PortalMessagesRouteImport } from './routes/portal/messages'
import { Route as PortalDashboardRouteImport } from './routes/portal/dashboard'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding/success'
import { Route as OnboardingStep5RouteImport } from './routes/onboarding/step-5'
import { Route as OnboardingStep4RouteImport } from './routes/onboarding/step-4'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding/step-3'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding/step-2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step-1'
import { Route as OnboardingDashboardRouteImport } from './routes/onboarding/dashboard'
import { Route as PortalProgramsIndexRouteImport } from './routes/portal/programs/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PortalProgramsSessionSessionIdRouteImport } from './routes/portal/programs/session/$sessionId'
import { Route as PortalProgramsModuleModuleIdRouteImport } from './routes/portal/programs/module/$moduleId'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsPrivacyRoute = TermsPrivacyRouteImport.update({
  id: '/terms-privacy',
  path: '/terms-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationFaqRoute = EducationFaqRouteImport.update({
  id: '/education-faq',
  path: '/education-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTrackingRoute = PortalTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => PortalRoute,
} as any)
const PortalScheduleRoute = PortalScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMoreRoute = PortalMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/onboarding/success',
  path: '/onboarding/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep5Route = OnboardingStep5RouteImport.update({
  id: '/onboarding/step-5',
  path: '/onboarding/step-5',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep4Route = OnboardingStep4RouteImport.update({
  id: '/onboarding/step-4',
  path: '/onboarding/step-4',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/onboarding/step-3',
  path: '/onboarding/step-3',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/onboarding/step-2',
  path: '/onboarding/step-2',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/onboarding/step-1',
  path: '/onboarding/step-1',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDashboardRoute = OnboardingDashboardRouteImport.update({
  id: '/onboarding/dashboard',
  path: '/onboarding/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProgramsIndexRoute = PortalProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => PortalRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProgramsSessionSessionIdRoute =
  PortalProgramsSessionSessionIdRouteImport.update({
    id: '/programs/session/$sessionId',
    path: '/programs/session/$sessionId',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalProgramsModuleModuleIdRoute =
  PortalProgramsModuleModuleIdRouteImport.update({
    id: '/programs/module/$moduleId',
    path: '/programs/module/$moduleId',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/education-faq': typeof EducationFaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/terms-privacy': typeof TermsPrivacyRoute
  '/verification': typeof VerificationRoute
  '/onboarding/dashboard': typeof OnboardingDashboardRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/onboarding/step-5': typeof OnboardingStep5Route
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/more': typeof PortalMoreRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal/tracking': typeof PortalTrackingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/portal/programs/': typeof PortalProgramsIndexRoute
  '/portal/programs/module/$moduleId': typeof PortalProgramsModuleModuleIdRoute
  '/portal/programs/session/$sessionId': typeof PortalProgramsSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/education-faq': typeof EducationFaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/terms-privacy': typeof TermsPrivacyRoute
  '/verification': typeof VerificationRoute
  '/onboarding/dashboard': typeof OnboardingDashboardRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/onboarding/step-5': typeof OnboardingStep5Route
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/more': typeof PortalMoreRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal/tracking': typeof PortalTrackingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/portal/programs': typeof PortalProgramsIndexRoute
  '/portal/programs/module/$moduleId': typeof PortalProgramsModuleModuleIdRoute
  '/portal/programs/session/$sessionId': typeof PortalProgramsSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/education-faq': typeof EducationFaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/terms-privacy': typeof TermsPrivacyRoute
  '/verification': typeof VerificationRoute
  '/onboarding/dashboard': typeof OnboardingDashboardRoute
  '/onboarding/step-1': typeof OnboardingStep1Route
  '/onboarding/step-2': typeof OnboardingStep2Route
  '/onboarding/step-3': typeof OnboardingStep3Route
  '/onboarding/step-4': typeof OnboardingStep4Route
  '/onboarding/step-5': typeof OnboardingStep5Route
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/more': typeof PortalMoreRoute
  '/portal/schedule': typeof PortalScheduleRoute
  '/portal/tracking': typeof PortalTrackingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/portal/programs/': typeof PortalProgramsIndexRoute
  '/portal/programs/module/$moduleId': typeof PortalProgramsModuleModuleIdRoute
  '/portal/programs/session/$sessionId': typeof PortalProgramsSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/education-faq'
    | '/features'
    | '/login'
    | '/portal'
    | '/terms-privacy'
    | '/verification'
    | '/onboarding/dashboard'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/step-5'
    | '/onboarding/success'
    | '/portal/dashboard'
    | '/portal/messages'
    | '/portal/more'
    | '/portal/schedule'
    | '/portal/tracking'
    | '/api/auth/$'
    | '/portal/programs/'
    | '/portal/programs/module/$moduleId'
    | '/portal/programs/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/education-faq'
    | '/features'
    | '/login'
    | '/portal'
    | '/terms-privacy'
    | '/verification'
    | '/onboarding/dashboard'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/step-5'
    | '/onboarding/success'
    | '/portal/dashboard'
    | '/portal/messages'
    | '/portal/more'
    | '/portal/schedule'
    | '/portal/tracking'
    | '/api/auth/$'
    | '/portal/programs'
    | '/portal/programs/module/$moduleId'
    | '/portal/programs/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/education-faq'
    | '/features'
    | '/login'
    | '/portal'
    | '/terms-privacy'
    | '/verification'
    | '/onboarding/dashboard'
    | '/onboarding/step-1'
    | '/onboarding/step-2'
    | '/onboarding/step-3'
    | '/onboarding/step-4'
    | '/onboarding/step-5'
    | '/onboarding/success'
    | '/portal/dashboard'
    | '/portal/messages'
    | '/portal/more'
    | '/portal/schedule'
    | '/portal/tracking'
    | '/api/auth/$'
    | '/portal/programs/'
    | '/portal/programs/module/$moduleId'
    | '/portal/programs/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EducationFaqRoute: typeof EducationFaqRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  TermsPrivacyRoute: typeof TermsPrivacyRoute
  VerificationRoute: typeof VerificationRoute
  OnboardingDashboardRoute: typeof OnboardingDashboardRoute
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  OnboardingStep3Route: typeof OnboardingStep3Route
  OnboardingStep4Route: typeof OnboardingStep4Route
  OnboardingStep5Route: typeof OnboardingStep5Route
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-privacy': {
      id: '/terms-privacy'
      path: '/terms-privacy'
      fullPath: '/terms-privacy'
      preLoaderRoute: typeof TermsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-faq': {
      id: '/education-faq'
      path: '/education-faq'
      fullPath: '/education-faq'
      preLoaderRoute: typeof EducationFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/tracking': {
      id: '/portal/tracking'
      path: '/tracking'
      fullPath: '/portal/tracking'
      preLoaderRoute: typeof PortalTrackingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/schedule': {
      id: '/portal/schedule'
      path: '/schedule'
      fullPath: '/portal/schedule'
      preLoaderRoute: typeof PortalScheduleRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/more': {
      id: '/portal/more'
      path: '/more'
      fullPath: '/portal/more'
      preLoaderRoute: typeof PortalMoreRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/onboarding/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-5': {
      id: '/onboarding/step-5'
      path: '/onboarding/step-5'
      fullPath: '/onboarding/step-5'
      preLoaderRoute: typeof OnboardingStep5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-4': {
      id: '/onboarding/step-4'
      path: '/onboarding/step-4'
      fullPath: '/onboarding/step-4'
      preLoaderRoute: typeof OnboardingStep4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-3': {
      id: '/onboarding/step-3'
      path: '/onboarding/step-3'
      fullPath: '/onboarding/step-3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-2': {
      id: '/onboarding/step-2'
      path: '/onboarding/step-2'
      fullPath: '/onboarding/step-2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step-1': {
      id: '/onboarding/step-1'
      path: '/onboarding/step-1'
      fullPath: '/onboarding/step-1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/dashboard': {
      id: '/onboarding/dashboard'
      path: '/onboarding/dashboard'
      fullPath: '/onboarding/dashboard'
      preLoaderRoute: typeof OnboardingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/programs/': {
      id: '/portal/programs/'
      path: '/programs'
      fullPath: '/portal/programs/'
      preLoaderRoute: typeof PortalProgramsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/programs/session/$sessionId': {
      id: '/portal/programs/session/$sessionId'
      path: '/programs/session/$sessionId'
      fullPath: '/portal/programs/session/$sessionId'
      preLoaderRoute: typeof PortalProgramsSessionSessionIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/programs/module/$moduleId': {
      id: '/portal/programs/module/$moduleId'
      path: '/programs/module/$moduleId'
      fullPath: '/portal/programs/module/$moduleId'
      preLoaderRoute: typeof PortalProgramsModuleModuleIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalMoreRoute: typeof PortalMoreRoute
  PortalScheduleRoute: typeof PortalScheduleRoute
  PortalTrackingRoute: typeof PortalTrackingRoute
  PortalProgramsIndexRoute: typeof PortalProgramsIndexRoute
  PortalProgramsModuleModuleIdRoute: typeof PortalProgramsModuleModuleIdRoute
  PortalProgramsSessionSessionIdRoute: typeof PortalProgramsSessionSessionIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDashboardRoute: PortalDashboardRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalMoreRoute: PortalMoreRoute,
  PortalScheduleRoute: PortalScheduleRoute,
  PortalTrackingRoute: PortalTrackingRoute,
  PortalProgramsIndexRoute: PortalProgramsIndexRoute,
  PortalProgramsModuleModuleIdRoute: PortalProgramsModuleModuleIdRoute,
  PortalProgramsSessionSessionIdRoute: PortalProgramsSessionSessionIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EducationFaqRoute: EducationFaqRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  TermsPrivacyRoute: TermsPrivacyRoute,
  VerificationRoute: VerificationRoute,
  OnboardingDashboardRoute: OnboardingDashboardRoute,
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  OnboardingStep3Route: OnboardingStep3Route,
  OnboardingStep4Route: OnboardingStep4Route,
  OnboardingStep5Route: OnboardingStep5Route,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
