import { Router } from "express";

import healthRoutes from "./health.routes";
import authRoutes from "./auth.routes";
import onboardingRoutes from "./onboarding.routes";
import programRoutes from "./program.routes";
import programSectionRoutes from "./program-section.routes";
import contentRoutes from "./content.routes";
import messageRoutes from "./message.routes";
import chatRoutes from "./chat.routes";
import bookingRoutes from "./booking.routes";
import videoRoutes from "./video.routes";
import adminRoutes from "./admin.routes";
import superAdminRoutes from "./super-admin.routes";
import mediaRoutes from "./media.routes";
import billingRoutes from "./billing.routes";
import nutritionRoutes from "./nutrition.routes";
import physioReferralRoutes from "./physio-referral.routes";
import ageExperienceRoutes from "./age-experience.routes";
import locationRoutes from "./location.routes";
import notificationRoutes from "./notification.routes";
import supportRoutes from "./support.routes";
import trainingContentV2Routes from "./training-content-v2.routes";
import openGraphRoutes from "./open-graph.routes";
import versionRoutes from "./version.routes";
import giphyRoutes from "./giphy.routes";
import runsRoutes from "./runs.routes";
import socialRoutes from "./social.routes";
import teamSocialRoutes from "./team-social.routes";
import teamRosterRoutes from "./team-roster.routes";
import activityRoutes from "./activity.routes";
import referralRoutes from "./referral.routes";
import portalRoutes from "./portal.routes";

const router = Router();

router.use(healthRoutes);
router.use(authRoutes);
router.use(onboardingRoutes);
router.use(programRoutes);
router.use(programSectionRoutes);
router.use(contentRoutes);
router.use(messageRoutes);
router.use(chatRoutes);
router.use(bookingRoutes);
router.use(videoRoutes);
router.use(mediaRoutes);
router.use(adminRoutes);
router.use(superAdminRoutes);
router.use(billingRoutes);
router.use(nutritionRoutes);
router.use(physioReferralRoutes);
	router.use(ageExperienceRoutes);
	router.use(locationRoutes);
	router.use(notificationRoutes);
router.use(supportRoutes);
router.use(trainingContentV2Routes);
router.use(openGraphRoutes);
router.use(versionRoutes);
router.use(giphyRoutes);
router.use(runsRoutes);
router.use(socialRoutes);
router.use(teamSocialRoutes);
router.use(teamRosterRoutes);
router.use(activityRoutes);
router.use(referralRoutes);
router.use(portalRoutes);

export default router;
