# fly.toml app configuration file generated for ph-platform-api on 2026-02-14T15:48:53+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ph-platform-api'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3001'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[deploy]
  release_command = 'npm run db:migrate:prod'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
